layout_spectrum: 0.5141569685656577
typography_spectrum: 0.0738824401050806
color:
  saturation: 0.1006734
  brandStrength: 0
  lightness: 0.239546
  brandColors:
    - '#FFFFFF'
    - '#0E0F0A'
    - '#FADA6B'
    - '#69351F'
    - '#BE9D50'
  rhythmicContrast: 0.5573476
title: ''
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
description: ''
cta:
  bucket: null
  version: null
  domain: null
favicon: null
analytics:
  twitter: null
  google: null
  facebook: null
name: Prayervolution
opengraph:
  image: null
  type: null
  appId: null
