title: ''
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
description: ''
color:
  saturation: 0.1006734
  brandStrength: 0.8787335
  lightness: 0.239546
  brandColors:
    - '#000000'
    - '#263248'
    - '#7E8AA2'
    - '#FFFFFF'
    - '#FF9800'
  rhythmicContrast: 0.01703754
cta:
  bucket: null
  version: null
  domain: null
favicon: null
analytics:
  twitter: null
  google: null
  facebook: null
name: Prayervolution
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.06511348
layout_spectrum: 0.9145758
