typography_spectrum: 0.7201639770064503
color:
  brandColors:
    - '#FFF8E3'
    - '#CCCC9F'
    - '#33332D'
    - '#9FB4CC'
    - '#DB4105'
  brandStrength: 0.5026811000425369
  lightness: 0.3920686994679272
  saturation: 0.9679416653234512
  rhythmicContrast: 0.0892148099374026
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.7837302919942886
analytics:
  google: null
  facebook: null
  twitter: null
name: Prayervolution
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: ''
description: ''
purpose: []
