layout_spectrum: 0.16915546264499426
typography_spectrum: 0.7252223808318377
color:
  brandColors:
    - '#FFF8E3'
    - '#CCCC9F'
    - '#33332D'
    - '#9FB4CC'
    - '#DB4105'
  brandStrength: 0.18215567781589925
  lightness: 0.23773617832921445
  saturation: 0.35688129160553217
  rhythmicContrast: 0.47763826325535774
opengraph:
  image: null
  type: null
  appId: null
analytics:
  google: null
  facebook: null
  twitter: null
name: Prayervolution
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: ''
description: ''
purpose: []
