title: ''
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
description: ''
color:
  saturation: 0.1006734
  brandStrength: 0.8787335
  lightness: 0.239546
  brandColors:
    - '#FFFFFF'
    - '#0E0F0A'
    - '#FADA6B'
    - '#69351F'
    - '#BE9D50'
  rhythmicContrast: 0.01703754
analytics:
  twitter: null
  google: null
  facebook: null
name: Prayervolution
favicon: null
cta:
  bucket: null
  version: null
  domain: null
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.06511348
layout_spectrum: 0.9145758
