layout_spectrum: 0.31176777789369226
typography_spectrum: 0.4192869660910219
color:
  brandColors:
    - '#000000'
    - '#263248'
    - '#7E8AA2'
    - '#FFFFFF'
    - '#FF9800'
  brandStrength: 0.7223123002331704
  lightness: 0.27987050148658454
  saturation: 0.10067338310182095
  rhythmicContrast: 0.01703754090704024
opengraph:
  image: null
  type: null
  appId: null
analytics:
  google: null
  facebook: null
  twitter: null
name: Prayervolution
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: ''
description: ''
purpose: []
